---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for ipr.ansible.xymon

# Server Manage required system packages [[[1
- name: Ensure required packages are in there desired state
  package:
    name: '{{ item }}'
    state: '{{ "present" if (xymon_server__deploy_state == "present") else "absent" }}'
    install_recommends: False
  with_flattened:
    - '{{ xymon_server__base_packages }}'

