---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for ipr-cnrs.xymon_server

# Server Manage required system packages [[[1
- name: Ensure required packages are in there desired state
  package:
    name: '{{ item }}'
    state: '{{ "present" if (xymon_server__deploy_state == "present") else "absent" }}'
    install_recommends: False
  with_flattened:
    - '{{ xymon_server__base_packages }}'


# Server Manage /etc configuration files [[[1

- name: Ensure /etc directory structure exists
  file:
    path: '/etc/xymon/{{ item.path }}'
    state: directory
  with_filetree: '{{ xymon_server__etc_src }}'
  when: item.state == 'directory'

- name: Ensure /etc files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: "/etc/xymon/{{ item.path | replace('.j2','') }}"
  with_filetree: '{{ xymon_server__etc_src }}'
  when: item.state == 'file'

# Manage services [[[1

- name: Manage Xymon server service
  service:
    name: 'xymon'
    state: '{{ "started" if (xymon_server__deploy_state == "present" and
                            (xymon_server__service_manage | d(True) | bool))
          else "stopped" }}'
    enabled: '{{ xymon_server__service_manage | d(True) | bool }}'

